---

- hosts: appserver
  remote_user: root

  tasks:
  - name: Install java version 8
    apt: 
      name: openjdk-8-jdk
      state: present
  - name: Create install directory
    file:
      state: directory
      path: /opt/helloworld-mvn/
      owner: root
      group: root
      mode: 0755

  - name: Copy files to remote host
    copy:
      src: files/helloworld.jar
      dest: /opt/helloworld-mvn/
      owner: root
      group: root
      mode: 0755

  - name: Execute app
    command: java -jar /opt/helloworld-mvn/helloworld.jar
